#ifndef MCNBT_BE_ENUMS_BIOME_HPP
#define MCNBT_BE_ENUMS_BIOME_HPP

namespace nbt
{

namespace be
{

enum Biome
{
    BIOME_OCEAN                                     = 0,
    BIOME_PLAINS                                    = 1,
    BIOME_DESERT                                    = 2,
    BIOME_EXTREME_HILLS                             = 3,
    BIOME_FOREST                                    = 4,
    BIOME_TAIGA                                     = 5,
    BIOME_SWAMPLAND                                 = 6,
    BIOME_RIVER                                     = 7,
    BIOME_HELL                                      = 8,
    BIOME_THE_END                                   = 9,
    BIOME_LEGACY_FROZEN_OCEAN                       = 10,
    BIOME_FROZEN_RIVER                              = 11,
    BIOME_ICE_PLAINS                                = 12,
    BIOME_ICE_MOUNTAINS                             = 13,
    BIOME_MUSHROOM_ISLAND                           = 14,
    BIOME_MUSHROOM_ISLAND_SHORE                     = 15,
    BIOME_BEACH                                     = 16,
    BIOME_DESERT_HILLS                              = 17,
    BIOME_FOREST_HILLS                              = 18,
    BIOME_TAIGA_HILLS                               = 19,
    BIOME_EXTREME_HILLS_EDGE                        = 20,
    BIOME_JUNGLE                                    = 21,
    BIOME_JUNGLE_HILLS                              = 22,
    BIOME_JUNGLE_EDGE                               = 23,
    BIOME_DEEP_OCEAN                                = 24,
    BIOME_STONE_BEACH                               = 25,
    BIOME_COLD_BEACH                                = 26,
    BIOME_BIRCH_FOREST                              = 27,
    BIOME_BIRCH_FOREST_HILLS                        = 28,
    BIOME_ROOFED_FOREST                             = 29,
    BIOME_COLD_TAIGA                                = 30,
    BIOME_COLD_TAIGA_HILLS                          = 31,
    BIOME_MEGA_TAIGA                                = 32,
    BIOME_MEGA_TAIGA_HILLS                          = 33,
    BIOME_EXTREME_HILLS_PLUS_TREES                  = 34,
    BIOME_SAVANNA                                   = 35,
    BIOME_SAVANNA_PLATEAU                           = 36,
    BIOME_MESA                                      = 37,
    BIOME_MESA_PLATEAU_STONE                        = 38,
    BIOME_MESA_PLATEAU                              = 39,
    BIOME_WARM_OCEAN                                = 40,
    BIOME_DEEP_WARM_OCEAN                           = 41,
    BIOME_LUKEWARM_OCEAN                            = 42,
    BIOME_DEEP_LUKEWARM_OCEAN                       = 43,
    BIOME_COLD_OCEAN                                = 44,
    BIOME_DEEP_COLD_OCEAN                           = 45,
    BIOME_FROZEN_OCEAN                              = 46,
    BIOME_DEEP_FROZEN_OCEAN                         = 47,
    BIOME_BAMBOO_JUNGLE                             = 48,
    BIOME_BAMBOO_JUNGLE_HILLS                       = 49,
    BIOME_SUNFLOWER_PLAINS                          = 129,
    BIOME_DESERT_MUTATED                            = 130,
    BIOME_EXTREME_HILLS_MUTATED                     = 131,
    BIOME_FLOWER_FOREST                             = 132,
    BIOME_TAIGA_MUTATED                             = 133,
    BIOME_SWAMPLAND_MUTATED                         = 134,
    BIOME_ICE_PLAINS_SPIKES                         = 140,
    BIOME_JUNGLE_MUTATED                            = 149,
    BIOME_JUNGLE_EDGE_MUTATED                       = 151,
    BIOME_BIRCH_FOREST_MUTATED                      = 155,
    BIOME_BIRCH_FOREST_HILLS_MUTATED                = 156,
    BIOME_ROOFED_FOREST_MUTATED                     = 157,
    BIOME_COLD_TAIGA_MUTATED                        = 158,
    BIOME_REDWOOD_TAIGA_MUTATED                     = 160,
    BIOME_REDWOOD_TAIGA_HILLS_MUTATED               = 161,
    BIOME_EXTREME_HILLS_PLUS_TREES_MUTATED          = 162,
    BIOME_SAVANNA_MUTATED                           = 163,
    BIOME_SAVANNA_PLATEAU_MUTATED                   = 164,
    BIOME_MESA_BRYCE                                = 165,
    BIOME_MESA_PLATEAU_STONE_MUTATED                = 166,
    BIOME_MESA_PLATEAU_MUTATED                      = 167,
    BIOME_SOULSAND_VALLEY                           = 178,
    BIOME_CRIMSON_FOREST                            = 179,
    BIOME_WARPED_FOREST                             = 180,
    BIOME_BASALT_DELTAS                             = 181,
    BIOME_JAGGED_PEAKS                              = 182,
    BIOME_FROZEN_PEAKS                              = 183,
    BIOME_SNOWY_SLOPES                              = 184,
    BIOME_GROVE                                     = 185,
    BIOME_MEADOW                                    = 186,
    BIOME_LUSH_CAVES                                = 187,
    BIOME_DRIPSTONE_CAVES                           = 188,
    BIOME_STONY_PEAKS                               = 189,
    BIOME_DEEP_DARK                                 = 190,
    BIOME_MANGROVE_SWAMP                            = 191,
    BIOME_CHERRY_GROVE                              = 192,
    BIOME_PALE_GARDEN                               = 193
};

} // namespace be

} // namespace nbt

#endif // !MCNBT_BE_ENUMS_BIOME_HPP
