#ifndef MCNBT_BE_ENUMS_EFFECT_HPP
#define MCNBT_BE_ENUMS_EFFECT_HPP

namespace nbt
{

namespace be
{

enum Effect
{
    EFFECT_NONE,
    EFFECT_SPEED,
    EFFECT_SLOWNESS,
    EFFECT_HASTE,
    EFFECT_MINING_FATIGUE,
    EFFECT_STRENGTH,
    EFFECT_INSTANT_HEALTH,
    EFFECT_INSTANT_DAMAGE,
    EFFECT_JUMP_BOOST,
    EFFECT_NAUSEA,
    EFFECT_REGENERATION,
    EFFECT_RESISTANCE,
    EFFECT_FIRE_RESISTANCE,
    EFFECT_WATER_BREATHING,
    EFFECT_INVISIBILITY,
    EFFECT_BLINDNESS,
    EFFECT_NIGHT_VISION,
    EFFECT_HUNGER,
    EFFECT_WEAKNESS,
    EFFECT_POISON,
    EFFECT_WITHER,
    EFFECT_HEALTH_BOOST,
    EFFECT_ABSORPTION,
    EFFECT_SATURATION,
    EFFECT_LEVITATION,
    EFFECT_FATAL_POISON,
    EFFECT_CONDUIT_POWER,
    EFFECT_SLOW_FALLING,
    EFFECT_BAD_OMEN,
    EFFECT_VILLAGE_HERO,
    EFFECT_DARKNESS,
    EFFECT_TRIAL_OMEN,
    EFFECT_WIND_CHARGED,
    EFFECT_WEAVING,
    EFFECT_OOZING,
    EFFECT_INFESTED,
    EFFECT_RAID_OMEN
};

} // namespace be

} // namespace nbt

#endif // !MCNBT_BE_ENUMS_EFFECT_HPP
