#ifndef MCNBT_BE_ENUMS_ENHANCE_HPP
#define MCNBT_BE_ENUMS_ENHANCE_HPP

namespace nbt
{

namespace be
{

enum Enhance
{
    ENHANCE_PROTECTION,
    ENHANCE_FIRE_PROTECTION,
    ENHANCE_FEATHER_FALLING,
    ENHANCE_BLAST_PROTECTION,
    ENHANCE_PROJECTILE_PROTECTION,
    ENHANCE_THORNS,
    ENHANCE_RESPIRATION,
    ENHANCE_DEPTH_STRIDER,
    ENHANCE_AQUA_AFFINITY,
    ENHANCE_SHARPNESS,
    ENHANCE_SMITE,
    ENHANCE_BANE_OF_ARTHROPODS,
    ENHANCE_KNOCKBACK,
    ENHANCE_FIRE_ASPECT,
    ENHANCE_LOOTING,
    ENHANCE_EFFICIENCY,
    ENHANCE_SILK_TOUCH,
    ENHANCE_UNBREAKING,
    ENHANCE_FORTUNE,
    ENHANCE_POWER,
    ENHANCE_PUNCH,
    ENHANCE_FLAME,
    ENHANCE_INFINITY,
    ENHANCE_LUCK_OF_THE_SEA,
    ENHANCE_LURE,
    ENHANCE_FROST_WALKER,
    ENHANCE_MENDING,
    ENHANCE_BINDING_CURSE,
    ENHANCE_VANISHING_CURSE,
    ENHANCE_IMPALING,
    ENHANCE_RIPTIDE,
    ENHANCE_LOYALTY,
    ENHANCE_CHANNELING,
    ENHANCE_MULTISHOT,
    ENHANCE_PIERCING,
    ENHANCE_QUICK_CHARGE,
    ENHANCE_SOUL_SPEED,
    ENHANCE_SWIFT_SNEAK,
    ENHANCE_WIND_BURST,
    ENHANCE_DENSITY,
    ENHANCE_BREACH
};

}

}

#endif // !MCNBT_BE_ENUMS_ENHANCE_HPP
